/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: Copyright (c) 2021 Jason Skuby (mytechtoybox.com)
 */

#pragma once

/* hotkeys */
#ifndef HOTKEY_01_AUX_MASK
#define HOTKEY_01_AUX_MASK 0
#endif
#ifndef HOTKEY_01_BUTTONS_MASK
#define HOTKEY_01_BUTTONS_MASK 768	// S1 | S2
#endif
#ifndef HOTKEY_01_DPAD_MASK
#define HOTKEY_01_DPAD_MASK 1		// Up
#endif
#ifndef HOTKEY_01_ACTION
#define HOTKEY_01_ACTION 4		// Home button
#endif

#ifndef HOTKEY_02_AUX_MASK
#define HOTKEY_02_AUX_MASK 0
#endif
#ifndef HOTKEY_02_BUTTONS_MASK
#define HOTKEY_02_BUTTONS_MASK 768	// S1 | S2
#endif
#ifndef HOTKEY_02_DPAD_MASK
#define HOTKEY_02_DPAD_MASK 2		// Down
#endif
#ifndef HOTKEY_02_ACTION
#define HOTKEY_02_ACTION 1		// dpad = DP mode
#endif

#ifndef HOTKEY_03_AUX_MASK
#define HOTKEY_03_AUX_MASK 0
#endif
#ifndef HOTKEY_03_BUTTONS_MASK
#define HOTKEY_03_BUTTONS_MASK 768	// S1 | S2
#endif
#ifndef HOTKEY_03_DPAD_MASK
#define HOTKEY_03_DPAD_MASK 4		// Left
#endif
#ifndef HOTKEY_03_ACTION
#define HOTKEY_03_ACTION 2		// dpad = LS mode
#endif

#ifndef HOTKEY_04_AUX_MASK
#define HOTKEY_04_AUX_MASK 0
#endif
#ifndef HOTKEY_04_BUTTONS_MASK
#define HOTKEY_04_BUTTONS_MASK 768	// S1 | S2
#endif
#ifndef HOTKEY_04_DPAD_MASK
#define HOTKEY_04_DPAD_MASK 8		// Right
#endif
#ifndef HOTKEY_04_ACTION
#define HOTKEY_04_ACTION 3		// dpad = RS mode
#endif

#ifndef HOTKEY_05_AUX_MASK
#define HOTKEY_05_AUX_MASK 0
#endif
#ifndef HOTKEY_05_BUTTONS_MASK
#define HOTKEY_05_BUTTONS_MASK 4608	// S2 | A1
#endif
#ifndef HOTKEY_05_DPAD_MASK
#define HOTKEY_05_DPAD_MASK 1		// Up
#endif
#ifndef HOTKEY_05_ACTION
#define HOTKEY_05_ACTION 6		// SOCD = up priority
#endif

#ifndef HOTKEY_06_AUX_MASK
#define HOTKEY_06_AUX_MASK 0
#endif
#ifndef HOTKEY_06_BUTTONS_MASK
#define HOTKEY_06_BUTTONS_MASK 4608	// S2 | A1
#endif
#ifndef HOTKEY_06_DPAD_MASK
#define HOTKEY_06_DPAD_MASK 2		// Down
#endif
#ifndef HOTKEY_06_ACTION
#define HOTKEY_06_ACTION 7		// SOCD = neutral
#endif

#ifndef HOTKEY_07_AUX_MASK
#define HOTKEY_07_AUX_MASK 0
#endif
#ifndef HOTKEY_07_BUTTONS_MASK
#define HOTKEY_07_BUTTONS_MASK 4608	// S2 | A1
#endif
#ifndef HOTKEY_07_DPAD_MASK
#define HOTKEY_07_DPAD_MASK 4		// Left
#endif
#ifndef HOTKEY_07_ACTION
#define HOTKEY_07_ACTION 8		// SOCD = last input wins
#endif

#ifndef HOTKEY_08_AUX_MASK
#define HOTKEY_08_AUX_MASK 0
#endif
#ifndef HOTKEY_08_BUTTONS_MASK
#define HOTKEY_08_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_08_DPAD_MASK
#define HOTKEY_08_DPAD_MASK 0
#endif
#ifndef HOTKEY_08_ACTION
#define HOTKEY_08_ACTION 0
#endif

#ifndef HOTKEY_09_AUX_MASK
#define HOTKEY_09_AUX_MASK 0
#endif
#ifndef HOTKEY_09_BUTTONS_MASK
#define HOTKEY_09_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_09_DPAD_MASK
#define HOTKEY_09_DPAD_MASK 0
#endif
#ifndef HOTKEY_09_ACTION
#define HOTKEY_09_ACTION 0
#endif

#ifndef HOTKEY_10_AUX_MASK
#define HOTKEY_10_AUX_MASK 0
#endif
#ifndef HOTKEY_10_BUTTONS_MASK
#define HOTKEY_10_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_10_DPAD_MASK
#define HOTKEY_10_DPAD_MASK 0
#endif
#ifndef HOTKEY_10_ACTION
#define HOTKEY_10_ACTION 0
#endif

#ifndef HOTKEY_11_AUX_MASK
#define HOTKEY_11_AUX_MASK 0
#endif
#ifndef HOTKEY_11_BUTTONS_MASK
#define HOTKEY_11_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_11_DPAD_MASK
#define HOTKEY_11_DPAD_MASK 0
#endif
#ifndef HOTKEY_11_ACTION
#define HOTKEY_11_ACTION 0
#endif

#ifndef HOTKEY_12_AUX_MASK
#define HOTKEY_12_AUX_MASK 0
#endif
#ifndef HOTKEY_12_BUTTONS_MASK
#define HOTKEY_12_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_12_DPAD_MASK
#define HOTKEY_12_DPAD_MASK 0
#endif
#ifndef HOTKEY_12_ACTION
#define HOTKEY_12_ACTION 0
#endif

#ifndef HOTKEY_13_AUX_MASK
#define HOTKEY_13_AUX_MASK 0
#endif
#ifndef HOTKEY_13_BUTTONS_MASK
#define HOTKEY_13_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_13_DPAD_MASK
#define HOTKEY_13_DPAD_MASK 0
#endif
#ifndef HOTKEY_13_ACTION
#define HOTKEY_13_ACTION 0
#endif

#ifndef HOTKEY_14_AUX_MASK
#define HOTKEY_14_AUX_MASK 0
#endif
#ifndef HOTKEY_14_BUTTONS_MASK
#define HOTKEY_14_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_14_DPAD_MASK
#define HOTKEY_14_DPAD_MASK 0
#endif
#ifndef HOTKEY_14_ACTION
#define HOTKEY_14_ACTION 0
#endif

#ifndef HOTKEY_15_AUX_MASK
#define HOTKEY_15_AUX_MASK 0
#endif
#ifndef HOTKEY_15_BUTTONS_MASK
#define HOTKEY_15_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_15_DPAD_MASK
#define HOTKEY_15_DPAD_MASK 0
#endif
#ifndef HOTKEY_15_ACTION
#define HOTKEY_15_ACTION 0
#endif

#ifndef HOTKEY_16_AUX_MASK
#define HOTKEY_16_AUX_MASK 0
#endif
#ifndef HOTKEY_16_BUTTONS_MASK
#define HOTKEY_16_BUTTONS_MASK 0
#endif
#ifndef HOTKEY_16_DPAD_MASK
#define HOTKEY_16_DPAD_MASK 0
#endif
#ifndef HOTKEY_16_ACTION
#define HOTKEY_16_ACTION 0
#endif

/* hotkey pin trigger mode (optional, default 0 = use button masks) */
#ifndef HOTKEY_01_USE_PIN_TRIGGER
#define HOTKEY_01_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_01_PIN_TRIGGER_MASK
#define HOTKEY_01_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_02_USE_PIN_TRIGGER
#define HOTKEY_02_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_02_PIN_TRIGGER_MASK
#define HOTKEY_02_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_03_USE_PIN_TRIGGER
#define HOTKEY_03_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_03_PIN_TRIGGER_MASK
#define HOTKEY_03_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_04_USE_PIN_TRIGGER
#define HOTKEY_04_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_04_PIN_TRIGGER_MASK
#define HOTKEY_04_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_05_USE_PIN_TRIGGER
#define HOTKEY_05_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_05_PIN_TRIGGER_MASK
#define HOTKEY_05_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_06_USE_PIN_TRIGGER
#define HOTKEY_06_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_06_PIN_TRIGGER_MASK
#define HOTKEY_06_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_07_USE_PIN_TRIGGER
#define HOTKEY_07_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_07_PIN_TRIGGER_MASK
#define HOTKEY_07_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_08_USE_PIN_TRIGGER
#define HOTKEY_08_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_08_PIN_TRIGGER_MASK
#define HOTKEY_08_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_09_USE_PIN_TRIGGER
#define HOTKEY_09_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_09_PIN_TRIGGER_MASK
#define HOTKEY_09_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_10_USE_PIN_TRIGGER
#define HOTKEY_10_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_10_PIN_TRIGGER_MASK
#define HOTKEY_10_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_11_USE_PIN_TRIGGER
#define HOTKEY_11_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_11_PIN_TRIGGER_MASK
#define HOTKEY_11_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_12_USE_PIN_TRIGGER
#define HOTKEY_12_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_12_PIN_TRIGGER_MASK
#define HOTKEY_12_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_13_USE_PIN_TRIGGER
#define HOTKEY_13_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_13_PIN_TRIGGER_MASK
#define HOTKEY_13_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_14_USE_PIN_TRIGGER
#define HOTKEY_14_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_14_PIN_TRIGGER_MASK
#define HOTKEY_14_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_15_USE_PIN_TRIGGER
#define HOTKEY_15_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_15_PIN_TRIGGER_MASK
#define HOTKEY_15_PIN_TRIGGER_MASK 0
#endif
#ifndef HOTKEY_16_USE_PIN_TRIGGER
#define HOTKEY_16_USE_PIN_TRIGGER 0
#endif
#ifndef HOTKEY_16_PIN_TRIGGER_MASK
#define HOTKEY_16_PIN_TRIGGER_MASK 0
#endif

/* per-button keyboard modifier masks (optional, default 0 = none) */
#ifndef KEY_DPAD_UP_MOD
#define KEY_DPAD_UP_MOD 0
#endif
#ifndef KEY_DPAD_DOWN_MOD
#define KEY_DPAD_DOWN_MOD 0
#endif
#ifndef KEY_DPAD_LEFT_MOD
#define KEY_DPAD_LEFT_MOD 0
#endif
#ifndef KEY_DPAD_RIGHT_MOD
#define KEY_DPAD_RIGHT_MOD 0
#endif
#ifndef KEY_BUTTON_B1_MOD
#define KEY_BUTTON_B1_MOD 0
#endif
#ifndef KEY_BUTTON_B2_MOD
#define KEY_BUTTON_B2_MOD 0
#endif
#ifndef KEY_BUTTON_B3_MOD
#define KEY_BUTTON_B3_MOD 0
#endif
#ifndef KEY_BUTTON_B4_MOD
#define KEY_BUTTON_B4_MOD 0
#endif
#ifndef KEY_BUTTON_L1_MOD
#define KEY_BUTTON_L1_MOD 0
#endif
#ifndef KEY_BUTTON_R1_MOD
#define KEY_BUTTON_R1_MOD 0
#endif
#ifndef KEY_BUTTON_L2_MOD
#define KEY_BUTTON_L2_MOD 0
#endif
#ifndef KEY_BUTTON_R2_MOD
#define KEY_BUTTON_R2_MOD 0
#endif
#ifndef KEY_BUTTON_S1_MOD
#define KEY_BUTTON_S1_MOD 0
#endif
#ifndef KEY_BUTTON_S2_MOD
#define KEY_BUTTON_S2_MOD 0
#endif
#ifndef KEY_BUTTON_L3_MOD
#define KEY_BUTTON_L3_MOD 0
#endif
#ifndef KEY_BUTTON_R3_MOD
#define KEY_BUTTON_R3_MOD 0
#endif
#ifndef KEY_BUTTON_A1_MOD
#define KEY_BUTTON_A1_MOD 0
#endif
#ifndef KEY_BUTTON_A2_MOD
#define KEY_BUTTON_A2_MOD 0
#endif
#ifndef KEY_BUTTON_A2
#define KEY_BUTTON_A2 0
#endif

// Default KEY_BUTTON_* values (used by KeyboardDriver fallback and KeyboardHostAddon)
// Boards no longer need to define these — per-pin KEYBOARD_KEYCODE_GPxx are the primary mechanism.
#ifndef KEY_DPAD_UP
#define KEY_DPAD_UP 0
#endif
#ifndef KEY_DPAD_DOWN
#define KEY_DPAD_DOWN 0
#endif
#ifndef KEY_DPAD_LEFT
#define KEY_DPAD_LEFT 0
#endif
#ifndef KEY_DPAD_RIGHT
#define KEY_DPAD_RIGHT 0
#endif
#ifndef KEY_BUTTON_B1
#define KEY_BUTTON_B1 0
#endif
#ifndef KEY_BUTTON_B2
#define KEY_BUTTON_B2 0
#endif
#ifndef KEY_BUTTON_R2
#define KEY_BUTTON_R2 0
#endif
#ifndef KEY_BUTTON_L2
#define KEY_BUTTON_L2 0
#endif
#ifndef KEY_BUTTON_B3
#define KEY_BUTTON_B3 0
#endif
#ifndef KEY_BUTTON_B4
#define KEY_BUTTON_B4 0
#endif
#ifndef KEY_BUTTON_R1
#define KEY_BUTTON_R1 0
#endif
#ifndef KEY_BUTTON_L1
#define KEY_BUTTON_L1 0
#endif
#ifndef KEY_BUTTON_S1
#define KEY_BUTTON_S1 0
#endif
#ifndef KEY_BUTTON_S2
#define KEY_BUTTON_S2 0
#endif
#ifndef KEY_BUTTON_L3
#define KEY_BUTTON_L3 0
#endif
#ifndef KEY_BUTTON_R3
#define KEY_BUTTON_R3 0
#endif
#ifndef KEY_BUTTON_A1
#define KEY_BUTTON_A1 0
#endif
#ifndef KEY_BUTTON_A2
#define KEY_BUTTON_A2 0
#endif
#ifndef KEY_BUTTON_FN
#define KEY_BUTTON_FN 0
#endif

// Per-pin keyboard keycode defaults (pin → direct HID keycode)
// KEYBOARD_KEYCODE_GPxx = explicit HID keycode for a pin
// KEYBOARD_MODIFIER_GPxx = modifier mask for a pin
// These take priority over the KEY_BUTTON_* by-action fallback in setKeyboardDefaults.
#ifndef KEYBOARD_KEYCODE_GP00
#define KEYBOARD_KEYCODE_GP00 0
#endif
#ifndef KEYBOARD_KEYCODE_GP01
#define KEYBOARD_KEYCODE_GP01 0
#endif
#ifndef KEYBOARD_KEYCODE_GP02
#define KEYBOARD_KEYCODE_GP02 0
#endif
#ifndef KEYBOARD_KEYCODE_GP03
#define KEYBOARD_KEYCODE_GP03 0
#endif
#ifndef KEYBOARD_KEYCODE_GP04
#define KEYBOARD_KEYCODE_GP04 0
#endif
#ifndef KEYBOARD_KEYCODE_GP05
#define KEYBOARD_KEYCODE_GP05 0
#endif
#ifndef KEYBOARD_KEYCODE_GP06
#define KEYBOARD_KEYCODE_GP06 0
#endif
#ifndef KEYBOARD_KEYCODE_GP07
#define KEYBOARD_KEYCODE_GP07 0
#endif
#ifndef KEYBOARD_KEYCODE_GP08
#define KEYBOARD_KEYCODE_GP08 0
#endif
#ifndef KEYBOARD_KEYCODE_GP09
#define KEYBOARD_KEYCODE_GP09 0
#endif
#ifndef KEYBOARD_KEYCODE_GP10
#define KEYBOARD_KEYCODE_GP10 0
#endif
#ifndef KEYBOARD_KEYCODE_GP11
#define KEYBOARD_KEYCODE_GP11 0
#endif
#ifndef KEYBOARD_KEYCODE_GP12
#define KEYBOARD_KEYCODE_GP12 0
#endif
#ifndef KEYBOARD_KEYCODE_GP13
#define KEYBOARD_KEYCODE_GP13 0
#endif
#ifndef KEYBOARD_KEYCODE_GP14
#define KEYBOARD_KEYCODE_GP14 0
#endif
#ifndef KEYBOARD_KEYCODE_GP15
#define KEYBOARD_KEYCODE_GP15 0
#endif
#ifndef KEYBOARD_KEYCODE_GP16
#define KEYBOARD_KEYCODE_GP16 0
#endif
#ifndef KEYBOARD_KEYCODE_GP17
#define KEYBOARD_KEYCODE_GP17 0
#endif
#ifndef KEYBOARD_KEYCODE_GP18
#define KEYBOARD_KEYCODE_GP18 0
#endif
#ifndef KEYBOARD_KEYCODE_GP19
#define KEYBOARD_KEYCODE_GP19 0
#endif
#ifndef KEYBOARD_KEYCODE_GP20
#define KEYBOARD_KEYCODE_GP20 0
#endif
#ifndef KEYBOARD_KEYCODE_GP21
#define KEYBOARD_KEYCODE_GP21 0
#endif
#ifndef KEYBOARD_KEYCODE_GP22
#define KEYBOARD_KEYCODE_GP22 0
#endif
#ifndef KEYBOARD_KEYCODE_GP23
#define KEYBOARD_KEYCODE_GP23 0
#endif
#ifndef KEYBOARD_KEYCODE_GP24
#define KEYBOARD_KEYCODE_GP24 0
#endif
#ifndef KEYBOARD_KEYCODE_GP25
#define KEYBOARD_KEYCODE_GP25 0
#endif
#ifndef KEYBOARD_KEYCODE_GP26
#define KEYBOARD_KEYCODE_GP26 0
#endif
#ifndef KEYBOARD_KEYCODE_GP27
#define KEYBOARD_KEYCODE_GP27 0
#endif
#ifndef KEYBOARD_KEYCODE_GP28
#define KEYBOARD_KEYCODE_GP28 0
#endif
#ifndef KEYBOARD_KEYCODE_GP29
#define KEYBOARD_KEYCODE_GP29 0
#endif

#ifndef KEYBOARD_MODIFIER_GP00
#define KEYBOARD_MODIFIER_GP00 0
#endif
#ifndef KEYBOARD_MODIFIER_GP01
#define KEYBOARD_MODIFIER_GP01 0
#endif
#ifndef KEYBOARD_MODIFIER_GP02
#define KEYBOARD_MODIFIER_GP02 0
#endif
#ifndef KEYBOARD_MODIFIER_GP03
#define KEYBOARD_MODIFIER_GP03 0
#endif
#ifndef KEYBOARD_MODIFIER_GP04
#define KEYBOARD_MODIFIER_GP04 0
#endif
#ifndef KEYBOARD_MODIFIER_GP05
#define KEYBOARD_MODIFIER_GP05 0
#endif
#ifndef KEYBOARD_MODIFIER_GP06
#define KEYBOARD_MODIFIER_GP06 0
#endif
#ifndef KEYBOARD_MODIFIER_GP07
#define KEYBOARD_MODIFIER_GP07 0
#endif
#ifndef KEYBOARD_MODIFIER_GP08
#define KEYBOARD_MODIFIER_GP08 0
#endif
#ifndef KEYBOARD_MODIFIER_GP09
#define KEYBOARD_MODIFIER_GP09 0
#endif
#ifndef KEYBOARD_MODIFIER_GP10
#define KEYBOARD_MODIFIER_GP10 0
#endif
#ifndef KEYBOARD_MODIFIER_GP11
#define KEYBOARD_MODIFIER_GP11 0
#endif
#ifndef KEYBOARD_MODIFIER_GP12
#define KEYBOARD_MODIFIER_GP12 0
#endif
#ifndef KEYBOARD_MODIFIER_GP13
#define KEYBOARD_MODIFIER_GP13 0
#endif
#ifndef KEYBOARD_MODIFIER_GP14
#define KEYBOARD_MODIFIER_GP14 0
#endif
#ifndef KEYBOARD_MODIFIER_GP15
#define KEYBOARD_MODIFIER_GP15 0
#endif
#ifndef KEYBOARD_MODIFIER_GP16
#define KEYBOARD_MODIFIER_GP16 0
#endif
#ifndef KEYBOARD_MODIFIER_GP17
#define KEYBOARD_MODIFIER_GP17 0
#endif
#ifndef KEYBOARD_MODIFIER_GP18
#define KEYBOARD_MODIFIER_GP18 0
#endif
#ifndef KEYBOARD_MODIFIER_GP19
#define KEYBOARD_MODIFIER_GP19 0
#endif
#ifndef KEYBOARD_MODIFIER_GP20
#define KEYBOARD_MODIFIER_GP20 0
#endif
#ifndef KEYBOARD_MODIFIER_GP21
#define KEYBOARD_MODIFIER_GP21 0
#endif
#ifndef KEYBOARD_MODIFIER_GP22
#define KEYBOARD_MODIFIER_GP22 0
#endif
#ifndef KEYBOARD_MODIFIER_GP23
#define KEYBOARD_MODIFIER_GP23 0
#endif
#ifndef KEYBOARD_MODIFIER_GP24
#define KEYBOARD_MODIFIER_GP24 0
#endif
#ifndef KEYBOARD_MODIFIER_GP25
#define KEYBOARD_MODIFIER_GP25 0
#endif
#ifndef KEYBOARD_MODIFIER_GP26
#define KEYBOARD_MODIFIER_GP26 0
#endif
#ifndef KEYBOARD_MODIFIER_GP27
#define KEYBOARD_MODIFIER_GP27 0
#endif
#ifndef KEYBOARD_MODIFIER_GP28
#define KEYBOARD_MODIFIER_GP28 0
#endif
#ifndef KEYBOARD_MODIFIER_GP29
#define KEYBOARD_MODIFIER_GP29 0
#endif
